### ISSUE TITLE
About the input dimension of fc1 of decoder

### ISSUE THREAD

**Issue by zijundeng** [laubonghaudoi/CapsNet_guide_PyTorch#1]
Hello, thanks for your code, which helps me strengthen the understanding of the capsnet. I have a question as follows.

For all the capsules, it seems better to share fc1 parameters of decoder (so the input dimension is 16 instead of 10 * 16). And this [repo](https://github.com/naturomics/CapsNet-Tensorflow) uses input dimension of 16. What is your consideration?

**Comment by laubonghaudoi** [comment]
Thanks for your correction. According to section 4.1 in the paper, which says *The output of the digit
capsule is fed into a decoder*, we can infer that only the output of one capsule, rather than outputs of all 16 capsules, is sent to the decoder. I doubt if there is any difference in the final outcome between these two implementations (since all other outputs are zeros). I'm working on it and might push an update later, sorry for the mistake.

**Comment by zijundeng** [comment]
客气了哈哈

**Comment by laubonghaudoi** [comment]
Fixed in #3.
